### ISSUE TITLE
Quick Questions

### ISSUE THREAD

**Issue by nmcbride** [crasm/dead-simple-home-manager#1]
I'm just getting started with Nix and home manger. I'm using it on Fedora Silverblue. I'm sorry if these are dumb questions.
Currently I'm using home manager with home.nix and wanted to switch to flakes. Normally home manager uses the home.nix file. Do we have to do anything special to tell it to use the flake? It seems as though here the flake is loading home.nix?

I see in home.nix there are checks for linux vs mac regarding packages. However in flake.nix outputs -> homeConfiguration there is not. Are we supposed to remove one of these, are they both evaluated?

Do you have an example showing this setup doing a bit more like pulling in other flakes and packages and such we can use as a reference?

Thank you.

**Comment by crasm** [comment]
FYI this is not an idiomatic flake setup, but it works for keeping my shellenv and dotfiles synced across platforms/machines with platform and device-specific tweaks. The flake.nix imports home.nix, which contains pretty much all of the configuration.

I have the alias `hs='home-manager switch --flake /Users/vczf/stuff/nix/home-manager` which is my directory that contains both the flake.nix and home.nix.

I haven't needed or tried to pull on other flakes TBH, since my use-case is intentionally simple.
